# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Hidden imports necesarios para Flask-SocketIO, eventlet y otras dependencias
hidden_imports = [
    'engineio.async_drivers.threading',
    'socketio',
    'engineio',
    'dns',
    'dns.resolver',
    'dns.asyncresolver',
    'dns.asyncbackend',
    'eventlet',
    'eventlet.hubs',
    'eventlet.green',
    'eventlet.greenthread',
    'eventlet.wsgi',
    'flask',
    'flask_socketio',
    'werkzeug',
    'jinja2',
    'win32gui',
    'win32con',
    'win32api',
    'pywintypes',
    'winreg',
    'pystray',
    'pystray._win32',
    'PIL',
    'PIL._tkinter_finder',
    'pyautogui',
    'pynput',
    'pynput.keyboard',
    'pynput.mouse',
    'pycaw',
    'customtkinter',
    'qrcode',
    'config',
    'utils',
    'input_detector',
    'socket_handlers',
    'routes',
]

a = Analysis(
    ['gui_app.py'],
    pathex=[],
    binaries=[],
    datas=[('src', 'src')],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'pytest',
        'setuptools',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PCRemoteControl',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src\\Logo.ico',
)
